### ISSUE TITLE
Style of the 404 Error Page

### ISSUE THREAD

**Issue by samiba6** [202306-NEA-DZ-FEW/StudentStore#112]
**Task Title:** 
Create a 404 Error Page
**Task Description:**
Design and implement a user-friendly 404 error page for the student store market website.

**Subtasks:**

- [x] Design the layout and content structure for the 404 page. While ensuring the page reflects the website's branding and style.

- [x] Add engaging content to lighten the error experience.

**Screenshots**
<img width="548" alt="image" src="https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/51706925/b92a6370-382b-483d-abbe-c922d64d9162">
**Link to the component on Figma**
Put the link here

**Comment by hocine1212** [comment]
I already worked on it and it's done #163
